### ISSUE TITLE
Exception to halt game engine

### ISSUE THREAD

**Issue by Tjorriemorrie** [EntelectChallenge/2016-Bomberman#12]
Is it possible to add a param to the run command to exit the program when a bot raises an exception?

**Comment by EntelectChallenge** [comment]
Hi Tjorriemorrie,

I can not think of an easy way to do this.  But if your require this functionality please feel free to do it your own version of the game engine.

**Comment by EntelectChallenge** [comment]
Hi Tjorriemorrie,

This functionality has now been included in the latest release.
