### ISSUE TITLE
Round Number is 1 for first round (0)

### ISSUE THREAD

**Issue by grantstephens** [EntelectChallenge/2016-Bomberman#16]
Hi

Not sure if this is an issue, but the round number is 1 on the first round, denoted as 0 in the log and then is still 1 for the actual 1st round- is the just limited to me?
If this is intentional, how should I go about determining a fresh game state if not by a round number of 0?

**Comment by EntelectChallenge** [comment]
Hi RexFuzzle,

How are you reading the round information?  Looking at the state.json and the map.txt files on the latest game engine (V1.2.4) the Current Round attribute is the same as the log directory number in every case on my side?

**Comment by grantstephens** [comment]
Ok, so the state.json and map.txt file in the round directory are correct, but the same files in the player's directory, i.e. logs/0/A/state.json shows a round of 1. The example bot reads this json, not the one in the directory above...
I have compiled this on ubuntu so not sure if that is causing the issue, but everything else seems to work.

**Comment by grantstephens** [comment]
Also subsequently found that the BombBag parameter also doesn't go to 0 when you place a bomb... Just need to confirm that it is definitely my system/ custom compile that is causing the issue

**Comment by EntelectChallenge** [comment]
Ok, I see what you mean.  It is not just you, I get it on my side as well.  The round's state.json is written write before the bot files are written and are executed, but when the round number is incremented between those two calls.

I will have to fix it, I cannot do that today, but will have a look at it tomorrow.  Or you can make the required changes and create a pull request?

**Comment by grantstephens** [comment]
Haha, sjoe, was a bit worried there. Thank you, I'll have a look, but my C# isn't... sharp.

**Comment by grantstephens** [comment]
Note: This has not fixed the BombBag bug, which i think is related, just haven't found where it is yet.

**Comment by EntelectChallenge** [comment]
Hi Rexfuzzle,

I fixed the bug with the round numbers and will most likely publish a new release tomorrow.  The bombag scenario is intentional, it is only on the map.txt that the bombag gets decremented, in the state.json you will have to calculate bombs planted - bombag size to get bombs available.  So to clarify, the map.txt indicates bombs available in the bomb bag, where the state.json indicates bombag size.
