### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by poinu** [EntelectChallenge/2016-Bomberman#18]
Hi,

We are interested in using this project as part of a project for a university course, but we noticed it has no license. Would it be possible to add an open source license?

Thank you!

PS. More info about projects without license [here](https://choosealicense.com/no-permission/).

**Comment by rishal-hurbans** [comment]
Hi. Are you interested in the Bomberman engine or the upcoming 2018 challenge engine? We will add the licences after we've determined the relevant licence for this type of project.

**Comment by poinu** [comment]
We are interested in the Bomberman engine only, however, I'm sure someone else will be interested in the other projects. Thank you :)

**Comment by rishal-hurbans** [comment]
We have updated the license on all repositories for the Entelect Challenge. You're free to use the engines for your course. Additionally, we'd love to see how it's being applied in your course content!

**Comment by EntelectChallenge** [comment]
@poinu Thanks for your interest. We hope everything is in order. Again, we'd like to see how you apply the code in your work.
