### ISSUE TITLE
Proposal for run argument in bot.json

### ISSUE THREAD

**Issue by wduminy** [EntelectChallenge/2016-Bomberman#6]
During the development of a bot, it would be useful for me (and I assume for others) to build the same .exe for different bots; and then to be able to test those using the game engine.

The engine can make this possible if I can give it an argument to pass on to the exe that identifies the bot on my side.  The `bot.json` file  seems to be a good place for me to specify this.

Maybe a new entry called `RunArgument`can be added -- like so:

```
{
    "Author":"John Doe",
    "Email":"john.doe@example.com",
    "NickName" :"John",
    "BotType": "CSharp",
    "ProjectLocation" : "",
    "RunFile" : "Reference\\bin\\Debug\\Reference.exe"
    "RunArgument": "variationZ"
}
```

Then, your bot will receive three arguments for every round in the game:
1. Your player key registered in the game
2. The directory for the current game files
3. The value of `RunArgument` (if it is not an empty string)

**Comment by EntelectChallenge** [comment]
Hi codespear,

We made the changes for this feature and will include it with the next release.
