### ISSUE TITLE
missing requirements.txt file

### ISSUE THREAD

**Issue by bifocalpirate** [EntelectChallenge/2016-Bomberman#8]
-- for the python bots

1] Maybe get users to install the requirements under a `virtualenv` then `site-packages` will be left clean.

2] For the python bots there is a missing requirements.txt file referred to in the documentation. When the file is ready am I suppose to use `pip` to get the dependencies as there seems to be missing command to execute the `install` option against `requirements.txt`

**Comment by EntelectChallenge** [comment]
Hi skillex581,

That is nice suggestion, we will look into this.  It will probably require some code changes on our side to compile the bots.  But I can see that this might be necessary to separate the libraries for the different bots.

Yes the command to execute is `pip install -r requirements.txt` I will fix the example on the website.

**Comment by Tjorriemorrie** [comment]
You need to specify the executable to start a script under env, and the game engine controls that. You will have to change the game engine to create an unique virtualenv for every player, then automatically install the requirements and then change the executable to that env.

That is optimal, as people can specify incompatible versions with other libs already installed.  For me just specifying a target dir is so much easier for now.

**Comment by EntelectChallenge** [comment]
Hi Tjorriemorrie,

Please see this thread:  [http://forum.entelect.co.za/thread/a-question-on-python/](http://forum.entelect.co.za/thread/a-question-on-python/)

**Comment by EntelectChallenge** [comment]
Hi skrillex581,

How spent quite a few days trying to get virtualenv working for the challenge, but it is just to limiting for our needs and fails very easily.  For this reason we will not be implementing this for the challenge this year.

If there are any python bots failing due to version conflicts we will have to handle it on a case by case basis.
